name: Documentation

on:
  push:
    branches:
      - main
      - anas-docs        
    tags: '*'
  pull_request:
  
jobs:
  call:
    uses: control-toolbox/CTActions/.github/workflows/documentation.yml@main
